bugfix for merge-other
yymao/adstex pull request #45
Opened 2024-08-16 04:38 UTC by syrte

Editing the property `bib.entries_dict` doesn't work. Use the underlying `bib._entries_dict` instead!

This wired bug is found by inserting the debugging code: 
```
            print("DEBUG:", key in bib.entries_dict, key in [_['ID'] for _ in bib.entries])
            print("{}: FOUND IN OTHER BIB SOURCE, MERGED".format(key))
```
I realized that editing the property `bib.entries_dict` will not change `bib._entries_dict`.

2024-08-16 21:58 UTC, syrte commented
Why editing the property `bib.entries_dict` does not work anymore:

In `bibtexparser.bibdatabase`,
```python
class BibDatabase(object):
    """
    Bibliographic database object that follows the data structure of a BibTeX file.
    """

    def __init__(self):
        #: List of BibTeX entries, for example `@book{...}`, `@article{...}`, etc. Each entry is a simple dict with
        #: BibTeX field-value pairs, for example `'author': 'Bird, R.B. and Armstrong, R.C. and Hassager, O.'` Each
        #: entry will always have the following dict keys (in addition to other BibTeX fields):
        #:
        #: * `ID` (BibTeX key)
        #: * `ENTRYTYPE` (entry type in lowercase, e.g. `book`, `article` etc.)
        self.entries = []
        self._entries_dict = {}
...
    def get_entry_dict(self):
        """Return a dictionary of BibTeX entries, where dict key is the BibTeX entry key.

        This method re-creates the dict every time it is called,
        hence subsequent calls should be avoided with large databases.
        """
        self._entries_dict = dict()
        for entry in self.entries:
            self._entries_dict[entry['ID']] = entry
        return self._entries_dict

    entries_dict = property(get_entry_dict)
```
Every call to `BibDatabase.entries_dict` is fresh. So any changes to `entries_dict` do not change the internal status of the database object.
Therefore, we should use `BibDatabase.entries` directly. `_entries_dict` is only provided for temporary use for convenience.

2024-08-18 01:44 UTC, yymao requested changes
Thanks for catching this issue.  Given the behavior of `entries_dict`, I wonder if we can just modify `entries` in this case. See my suggested edit (I have not tested it).

2024-08-18 19:36 UTC, syrte commented on adstex.py
> +            bib.entries = list(bib._entries_dict.values())
Make sense to me.
It works in my examples.

2024-08-19 01:32 UTC, yymao approved these changes
Thanks for testing!

2024-08-19 01:33 UTC, merged

2024-08-19 21:32 UTC, syrte commented on adstex.py
> +            bib.entries = list(bib._entries_dict.values())
just realized that I could have simply accepted your suggested edit
first time met this function :)